# Generated by Django 2.2.14 on 2020-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0003_learningcontext_entrance_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesectionsequence',
            name='is_practice_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='is_proctored_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='is_timed_exam',
            field=models.BooleanField(default=False),
        ),
    ]
